#!/usr/bin/env python3
"""install.py — one-shot installer for the twss batch-approval hook + CLI.

Cross-platform (macOS, Linux, Windows) and shell-agnostic: the shim is a PATH
executable, not an alias, so it works from bash, zsh, fish, Git Bash, cmd, and
PowerShell alike. Idempotent — safe to re-run any time.

Run this YOURSELF (via the ! prefix in Claude Code): installing executables
onto PATH, hooks, and settings is enforcement surface, and agents are expected
to be blocked from it — the same rule that keeps `twss approve` a human act.
One user-run command replaces the old copy-a-file / hand-merge-JSON dance; the
consent act is running this installer, not performing each edit by hand.

What one run does:
  1. Locates the vault (BBB_VAULT_ROOT / CLAUDE_PROJECT_DIR / walk-up to a
     directory containing .claude/).
  2. Copies twss.py (from this skill folder) to <vault>/.claude/hooks/twss.py.
  3. Registers the PreToolUse hook in <vault>/.claude/settings.local.json —
     machine wiring, so absolute paths are correct there, pinned to THIS
     python (sys.executable). That immunises the hook against a stale session
     PATH and against the Windows Store python stub, which prints "Python was
     not found" instead of running anything. An existing registration in
     settings.json or settings.local.json is respected, never duplicated.
  4. Writes the `twss` shim(s) into a PATH directory (override:
     TWSS_INSTALL_DIR):
       macOS   : /opt/homebrew/bin, else /usr/local/bin, else ~/.local/bin
       Linux   : ~/.local/bin
       Windows : %USERPROFILE%\\bin (sh shim for Git Bash + twss.cmd for
                 cmd/PowerShell), and appends that directory to the user PATH
                 in the registry when missing (skip with --no-path). Already
                 open terminals keep their old PATH — the long form
                 `python .claude/hooks/twss.py ...` always works.
  5. Runs the acceptance tests (test_twss.py; skip with --no-test) and shows
     `twss status`, so a green install is a proven one.

Afterwards, restart the Claude Code session (claude --continue) to arm the
hook. /hooks edits hook config; it does not re-arm the running session.

Flags: --no-path (leave the Windows user PATH alone), --no-test.
Stdlib only. Run with python3 (macOS/Linux) or python / py (Windows).
"""

import json
import os
import platform
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent
HOOK_SRC = SKILL_DIR / "twss.py"
IS_WINDOWS = platform.system() == "Windows"

SH_SHIM = """#!/bin/sh
# twss — BBB vault batch-approval CLI shim (generated by install.py)
# Approval discipline: run `twss approve` YOURSELF via the ! prefix in Claude Code.
PY="{py}"
TWSS="{twss_py}"
if [ -x "$PY" ]; then exec "$PY" "$TWSS" "$@"; fi
if command -v python3 >/dev/null 2>&1; then exec python3 "$TWSS" "$@"; fi
exec python "$TWSS" "$@"
"""

CMD_SHIM = ("@echo off\r\n"
            "rem twss - BBB vault batch-approval CLI shim (generated by install.py)\r\n"
            "\"{py}\" \"{twss_py}\" %*\r\n")


def fwd(p) -> str:
    """Forward-slashed absolute path: valid in Git Bash, cmd, and PowerShell."""
    return str(p).replace("\\", "/")


def q(s: str) -> str:
    return f'"{s}"' if " " in s else s


def norm(p) -> str:
    return os.path.normcase(os.path.normpath(str(p)))


def find_vault():
    """Vault root = env var, else nearest ancestor with a .claude/ directory.

    The walk-up deliberately skips $HOME: ~/.claude is Claude Code's *user*
    config directory, not a project, and from anywhere under the home tree
    (a temp dir included) it would otherwise be the match — installing a
    vault hook into user config, where it does not belong.
    """
    for var in ("BBB_VAULT_ROOT", "CLAUDE_PROJECT_DIR"):
        v = os.environ.get(var)
        if v and (Path(v) / ".claude").is_dir():
            return Path(v).resolve()
    home = Path.home().resolve()
    here = Path.cwd().resolve()
    for cand in (here, *here.parents):
        if cand == home:
            continue
        if (cand / ".claude").is_dir():
            return cand
    return None


def install_hook_file(vault: Path) -> str:
    """Copy the hook into the vault. Returns installed|updated|unchanged."""
    dst = vault / ".claude" / "hooks" / "twss.py"
    src_bytes = HOOK_SRC.read_bytes()
    if dst.exists():
        if dst.read_bytes() == src_bytes:
            return "unchanged"
        dst.write_bytes(src_bytes)
        return "updated"
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_bytes(src_bytes)
    return "installed"


def registered_in(settings_path: Path):
    """The twss PreToolUse command in this settings file, or None."""
    try:
        cfg = json.loads(settings_path.read_text(encoding="utf-8"))
        for entry in cfg.get("hooks", {}).get("PreToolUse", []):
            for h in entry.get("hooks", []):
                if "twss.py" in h.get("command", ""):
                    return h["command"]
    except Exception:
        pass
    return None


def interpreter_works(command: str):
    """Can the interpreter in a registered hook command actually run Python?

    A registration is not proof of a working hook. The failure this catches is
    silent by design: the hook fails closed, so a dead interpreter looks exactly
    like "nothing was approved" — the user approves a queue and still gets
    prompted for every line, with no error anywhere. On Windows, bare `python`
    and `python3` usually resolve to the Microsoft Store stub (exit 9009,
    "Python was not found"), and Windows Python installs ship no python3.exe at
    all, so `python3` is the more likely of the two to be a stub.

    Returns (ok, detail).
    """
    try:
        interp = shlex.split(command, posix=True)[0]
    except Exception:
        return False, "unparseable command"
    resolved = interp if os.path.isabs(interp) else (shutil.which(interp) or "")
    if not resolved or not Path(resolved).exists():
        return False, f"{interp!r} does not resolve to an executable"
    try:
        proc = subprocess.run([resolved, "-c", "pass"],
                              capture_output=True, text=True, timeout=20)
    except Exception as e:
        return False, f"{interp!r} could not be run ({e})"
    if proc.returncode != 0:
        why = (proc.stderr or proc.stdout or "").strip().splitlines()
        hint = why[0] if why else f"exit {proc.returncode}"
        return False, f"{interp!r} is not a working interpreter: {hint}"
    return True, resolved


def drop_registrations(settings_path: Path) -> bool:
    """Remove every twss PreToolUse entry from a settings file."""
    try:
        cfg = json.loads(settings_path.read_text(encoding="utf-8"))
    except Exception:
        return False
    pre = cfg.get("hooks", {}).get("PreToolUse", [])
    kept = []
    for entry in pre:
        hooks = [h for h in entry.get("hooks", [])
                 if "twss.py" not in h.get("command", "")]
        if hooks:
            entry["hooks"] = hooks
            kept.append(entry)
        elif not entry.get("hooks"):
            kept.append(entry)
    if kept == pre:
        return False
    cfg["hooks"]["PreToolUse"] = kept
    if not cfg["hooks"]["PreToolUse"]:
        del cfg["hooks"]["PreToolUse"]
    if not cfg["hooks"]:
        del cfg["hooks"]
    settings_path.write_text(json.dumps(cfg, indent=2) + "\n", encoding="utf-8")
    return True


def write_registration(local: Path, hook_py: Path) -> str:
    command = f"{q(fwd(sys.executable))} {q(fwd(hook_py))} hook"
    try:
        cfg = json.loads(local.read_text(encoding="utf-8"))
    except FileNotFoundError:
        cfg = {}
    cfg.setdefault("hooks", {}).setdefault("PreToolUse", []).append({
        "matcher": "Bash",
        "hooks": [{"type": "command", "command": command, "timeout": 10}],
    })
    local.write_text(json.dumps(cfg, indent=2) + "\n", encoding="utf-8")
    return command


def register_hook(vault: Path, hook_py: Path, repair: bool):
    """Ensure a WORKING PreToolUse registration exists. Returns (status, where, notes).

    New registrations go in settings.local.json with an absolute path pinned to
    this interpreter (sys.executable). That file is the one the machine writes
    for itself (ADR-0013), which is what makes an absolute path safe there, and
    the pin means a stale PATH or a Store stub cannot silently kill enforcement.

    settings.json is the wrong home for it, but NOT because it syncs — neither
    file reaches another machine, since Obsidian Sync moves no dot-files
    (ADR-0038 Context). The reason is ownership: the vault root's settings.json
    arrives as a copy of bbb-vault-setup/assets/claude/settings.json at machine
    registration, so a machine-resolved interpreter written there is liable to be
    erased by the next re-copy — silently, and a hook that stops existing fails
    closed exactly like one that declined.

    An existing registration is validated, not trusted. A broken or misplaced
    one is reported and left alone unless --repair is given, because rewriting
    another machine's enforcement config is the user's call, not the
    installer's.
    """
    shared = vault / ".claude" / "settings.json"
    local = vault / ".claude" / "settings.local.json"
    notes = []
    for p in (shared, local):
        existing = registered_in(p)
        if not existing:
            continue
        ok, detail = interpreter_works(existing)
        misplaced = p == shared
        if ok and not misplaced:
            return "already registered and working", p, notes
        if ok and misplaced:
            notes.append(f"registration lives in {p.name}, which is an ASSET COPY"
                         " — machine registration re-copies it, silently erasing a"
                         " hook added here. It works today; it is one re-copy from"
                         " not existing. Move it with --repair.")
        else:
            notes.append(f"registration in {p.name} is BROKEN: {detail}."
                         " The hook fails closed, so twss silently never allows"
                         " anything. Fix it with --repair.")
        notes.append(f"  current: {existing}")
        if not repair:
            return "already registered (NOT healthy — see below)", p, notes
        drop_registrations(p)
        cmd = write_registration(local, hook_py)
        notes.append(f"  repaired: moved to {local.name} as: {cmd}")
        return "repaired", local, notes
    write_registration(local, hook_py)
    return "registered", local, notes


def pick_dir():
    override = os.environ.get("TWSS_INSTALL_DIR")
    if override:
        return Path(override)
    if IS_WINDOWS:
        return Path.home() / "bin"
    if platform.system() == "Darwin":
        for d in ("/opt/homebrew/bin", "/usr/local/bin"):
            if Path(d).is_dir() and os.access(d, os.W_OK):
                return Path(d)
    return Path.home() / ".local" / "bin"


def write_shims(target: Path, hook_py: Path):
    target.mkdir(parents=True, exist_ok=True)
    shim = target / "twss"
    shim.write_text(SH_SHIM.format(py=fwd(sys.executable), twss_py=fwd(hook_py)),
                    encoding="utf-8", newline="\n")
    shim.chmod(shim.stat().st_mode | 0o755)
    written = [shim]
    if IS_WINDOWS:
        cmd = target / "twss.cmd"
        cmd.write_text(CMD_SHIM.format(py=sys.executable, twss_py=hook_py),
                       encoding="utf-8", newline="")
        written.append(cmd)
    return written


def on_live_path(directory: Path) -> bool:
    entries = os.environ.get("PATH", "").split(os.pathsep)
    return any(norm(e) == norm(directory) for e in entries if e)


def ensure_user_path(target: Path) -> str:
    """Windows only: add target to the HKCU user PATH if missing.
    Returns present|added|failed:<why>. New terminals see it; open ones don't.
    """
    try:
        import winreg
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment", 0,
                            winreg.KEY_READ | winreg.KEY_SET_VALUE) as key:
            try:
                val, typ = winreg.QueryValueEx(key, "Path")
            except FileNotFoundError:
                val, typ = "", winreg.REG_EXPAND_SZ
            entries = [e for e in val.split(";") if e]
            if any(norm(os.path.expandvars(e)) == norm(target) for e in entries):
                return "present"
            new = (val.rstrip(";") + ";" if val else "") + str(target)
            winreg.SetValueEx(key, "Path", 0, typ, new)
    except Exception as e:
        return f"failed:{e}"
    try:  # tell running Explorer/new shells the environment changed
        import ctypes
        ctypes.windll.user32.SendMessageTimeoutW(
            0xFFFF, 0x001A, 0, "Environment", 0x0002, 5000, None)
    except Exception:
        pass
    return "added"


def run_tests() -> int:
    test = SKILL_DIR / "test_twss.py"
    proc = subprocess.run([sys.executable, str(test)],
                          capture_output=True, text=True)
    tail = [l for l in proc.stdout.splitlines() if l.strip()][-1:] or ["(no output)"]
    print(f"  {'ok  ' if proc.returncode == 0 else 'FAIL'}  self-test: {tail[0]}")
    if proc.returncode != 0:
        print(proc.stdout)
        print(proc.stderr, file=sys.stderr)
    return proc.returncode


def main() -> int:
    args = set(sys.argv[1:])
    vault = find_vault()
    if vault is None:
        print("twss install: vault not found (no .claude/ directory here or above;"
              " set BBB_VAULT_ROOT or run from inside the vault)")
        return 5

    print(f"twss install: vault {vault}")
    print(f"  ok    python {fwd(sys.executable)} (pinned into hook and shims)")

    hook_py = vault / ".claude" / "hooks" / "twss.py"
    print(f"  ok    hook {install_hook_file(vault)}: {hook_py}")

    status, where, notes = register_hook(vault, hook_py, "--repair" in args)
    mark = "warn" if "NOT healthy" in status else "ok  "
    print(f"  {mark}  PreToolUse hook {status} in {where.name}")
    for n in notes:
        print(f"        {n}")
    unhealthy = "NOT healthy" in status

    target = pick_dir()
    for w in write_shims(target, hook_py):
        print(f"  ok    wrote {w}")

    live = on_live_path(target)
    if IS_WINDOWS and "--no-path" not in args:
        # Deliberately independent of the live-shell check: Git Bash synthesizes
        # ~/bin onto its own PATH, so running from Git Bash (which is where the
        # ! prefix lands) makes the shim look installed while cmd and PowerShell
        # — the very shells twss.cmd exists for — still cannot find it. Only the
        # registry entry covers them.
        result = ensure_user_path(target)
        if result == "added":
            print(f"  ok    added {target} to the user PATH (registry). New terminals"
                  " see it; already-open ones do not.")
        elif result == "present":
            print(f"  ok    {target} is in the user PATH (registry)")
        else:
            print(f"  warn  could not edit user PATH ({result}); add {target} manually:"
                  " System Properties > Environment Variables")
        if live:
            print(f"  ok    {target} is also on PATH in this shell")
        else:
            print("  note  not on this shell's PATH yet — until a new terminal, use"
                  f" the long form: python \"{fwd(hook_py)}\" status")
    elif live:
        print(f"  ok    {target} is on PATH in this shell")
    else:
        print(f"  warn  {target} is not on PATH. Fix per shell:")
        print(f"          bash : echo 'export PATH=\"{target}:$PATH\"' >> ~/.bashrc")
        print(f"          zsh  : echo 'export PATH=\"{target}:$PATH\"' >> ~/.zshrc")
        print(f"          fish : fish_add_path {target}")
        if IS_WINDOWS:  # only reachable with --no-path
            print("          Windows: re-run without --no-path, or add it via"
                  " System Properties > Environment Variables")

    failed = 0
    if "--no-test" not in args:
        failed = run_tests()

    env = dict(os.environ)
    env["CLAUDE_PROJECT_DIR"] = str(vault)
    proc = subprocess.run([sys.executable, str(hook_py), "status"],
                          capture_output=True, text=True, env=env)
    first = proc.stdout.strip().splitlines()[0] if proc.stdout.strip() else "status produced no output"
    print(f"  {'ok  ' if proc.returncode == 0 else 'warn'}  {first}")

    if unhealthy:
        print("INCOMPLETE: the shims and hook file are in place, but the hook"
              " registration above is not healthy — re-run with --repair to"
              " rewrite it, then RESTART the session (claude --continue).")
        return 2
    # /hooks is a config editor: a hook registered after a session started loads
    # at the NEXT session start. Saying "/hooks (or restart)" hands the reader the
    # cheaper half, which is the half that does not work — f76afc8 fixed this in
    # SKILL.md and in the docstring above, and missed the two printed strings.
    print("done. RESTART the session to arm the hook: claude --continue "
          "(/hooks edits config; it does not re-arm a running session). Then: twss status")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
