#!/usr/bin/env python3
"""install.py — install the `twss` command shim for the current machine.

Cross-platform (macOS, Linux, Windows) and shell-agnostic: the shim is a PATH
executable, not an alias, so it works from bash, zsh, fish, Git Bash, cmd, and
PowerShell alike. Idempotent — safe to re-run.

Run this YOURSELF (via the ! prefix in Claude Code): installing executables
onto PATH is enforcement surface, and agents are expected to be blocked from
doing it — the same rule that keeps `twss approve` a human act.

What it does:
  1. Locates the vault (BBB_VAULT_ROOT / CLAUDE_PROJECT_DIR / walk-up) and its
     .claude/hooks/twss.py.
  2. Picks a per-OS PATH directory (override: TWSS_INSTALL_DIR):
       macOS   : /opt/homebrew/bin, else /usr/local/bin, else ~/.local/bin
       Linux   : ~/.local/bin
       Windows : %USERPROFILE%\\bin  (sh shim for Git Bash + twss.cmd for cmd/PS)
  3. Writes the shim(s), marks executable, warns if the directory is not on
     PATH (with per-shell fix hints).
  4. Verifies the PreToolUse hook is registered in the vault's
     .claude/settings.json and reports — it never edits settings itself.

Stdlib only. Run with python3 (macOS/Linux) or python (Windows).
"""

import json
import os
import platform
import sys
from pathlib import Path

SH_SHIM = """#!/bin/sh
# twss — BBB vault batch-approval CLI shim (generated by install.py)
# Approval discipline: run `twss approve` YOURSELF via the ! prefix in Claude Code.
TWSS="{twss_py}"
if command -v python3 >/dev/null 2>&1; then exec python3 "$TWSS" "$@"; fi
exec python "$TWSS" "$@"
"""

CMD_SHIM = "@echo off\r\nrem twss - BBB vault batch-approval CLI shim (generated by install.py)\r\npython \"{twss_py}\" %*\r\n"


def find_vault():
    for var in ("BBB_VAULT_ROOT", "CLAUDE_PROJECT_DIR"):
        v = os.environ.get(var)
        if v and (Path(v) / ".claude" / "hooks" / "twss.py").exists():
            return Path(v).resolve()
    here = Path.cwd().resolve()
    for cand in (here, *here.parents):
        if (cand / ".claude" / "hooks" / "twss.py").exists():
            return cand
    return None


def pick_dir():
    override = os.environ.get("TWSS_INSTALL_DIR")
    if override:
        return Path(override), platform.system() == "Windows"
    sysname = platform.system()
    if sysname == "Windows":
        return Path.home() / "bin", True
    if sysname == "Darwin":
        for d in ("/opt/homebrew/bin", "/usr/local/bin"):
            if Path(d).is_dir() and os.access(d, os.W_OK):
                return Path(d), False
    return Path.home() / ".local" / "bin", False


def on_path(directory: Path) -> bool:
    entries = os.environ.get("PATH", "").split(os.pathsep)
    want = str(directory)
    return any(os.path.normcase(os.path.normpath(e)) == os.path.normcase(os.path.normpath(want))
               for e in entries if e)


def hook_registered(vault: Path) -> bool:
    settings = vault / ".claude" / "settings.json"
    try:
        cfg = json.loads(settings.read_text(encoding="utf-8"))
        for entry in cfg.get("hooks", {}).get("PreToolUse", []):
            for h in entry.get("hooks", []):
                if "twss.py" in h.get("command", ""):
                    return True
    except Exception:
        pass
    return False


def main() -> int:
    vault = find_vault()
    if vault is None:
        print("twss install: vault not found (need .claude/hooks/twss.py; set BBB_VAULT_ROOT"
              " or run from inside the vault)")
        return 5
    twss_py = vault / ".claude" / "hooks" / "twss.py"
    target, is_windows = pick_dir()
    target.mkdir(parents=True, exist_ok=True)

    shim = target / "twss"
    shim.write_text(SH_SHIM.format(twss_py=twss_py), encoding="utf-8", newline="\n")
    shim.chmod(shim.stat().st_mode | 0o755)
    written = [str(shim)]
    if is_windows:
        cmd = target / "twss.cmd"
        cmd.write_text(CMD_SHIM.format(twss_py=twss_py), encoding="utf-8", newline="")
        written.append(str(cmd))

    print(f"twss install: vault {vault}")
    for w in written:
        print(f"  ok    wrote {w}")

    if not on_path(target):
        print(f"  warn  {target} is not on PATH. Fix per shell:")
        print(f"          bash : echo 'export PATH=\"{target}:$PATH\"' >> ~/.bashrc")
        print(f"          zsh  : echo 'export PATH=\"{target}:$PATH\"' >> ~/.zshrc")
        print(f"          fish : fish_add_path {target}")
        if is_windows:
            print("          Windows: System Properties > Environment Variables >"
                  f" add {target} to the user PATH (or use Git Bash, which includes ~/bin)")
    else:
        print(f"  ok    {target} is on PATH")

    if hook_registered(vault):
        print("  ok    PreToolUse hook registered in .claude/settings.json")
    else:
        interp = "python" if is_windows else "python3"
        print("  warn  hook NOT registered — merge this into <vault>/.claude/settings.json"
              " (a human edit, by design):")
        print(json.dumps({"hooks": {"PreToolUse": [{"matcher": "Bash", "hooks": [
            {"type": "command",
             "command": f"{interp} \"$CLAUDE_PROJECT_DIR/.claude/hooks/twss.py\" hook",
             "timeout": 10}]}]}}, indent=2))

    print("done. Try: twss status")
    return 0


if __name__ == "__main__":
    sys.exit(main())
